import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClassesProvider } from "@/lib/classes/provider";
import { DashboardDataProvider } from "@/lib/dashboard/provider";
import GeneralSettingsDialog from "@/components/sidebar/GeneralSettingsDialogue"; // <-- mount once globally
import { SEED_CLASSES } from "@/lib/seed/data";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClassesProvider seed={SEED_CLASSES}>
          <DashboardDataProvider>
            {children}
            {/* Render once so the sidebar can open it from anywhere */}
            <GeneralSettingsDialog />
          </DashboardDataProvider>
        </ClassesProvider>
      </body>
    </html>
  );
}
